### ISSUE TITLE
Add license file (MIT)

### ISSUE THREAD

**Issue by kolen** [kellerkindt/pcd8544#3]
If this code is really under MIT license, as indicated in `Cargo.toml`

https://github.com/kellerkindt/pcd8544/blob/fdaae4823f72ea4c2e977fb7926914a656e8ac47/Cargo.toml#L9

Can you add a `LICENSE` file too?

**Comment by kellerkindt** [comment]
Done in 1defb9a0d81231109af884d295878be42bed3978 :)
